//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyKawsay_ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_KawsayEntities : DbContext
    {
        public BD_KawsayEntities()
            : base("name=BD_KawsayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TB_ADMINISTRADOR> TB_ADMINISTRADOR { get; set; }
        public virtual DbSet<TB_ALMACEN> TB_ALMACEN { get; set; }
        public virtual DbSet<TB_ALMACENAMIENTO> TB_ALMACENAMIENTO { get; set; }
        public virtual DbSet<TB_CLIENTE> TB_CLIENTE { get; set; }
        public virtual DbSet<TB_HERRAMIENTA> TB_HERRAMIENTA { get; set; }
        public virtual DbSet<TB_INSTALACION> TB_INSTALACION { get; set; }
        public virtual DbSet<TB_MANTENIMIENTO> TB_MANTENIMIENTO { get; set; }
        public virtual DbSet<TB_PROGRAMACION> TB_PROGRAMACION { get; set; }
        public virtual DbSet<TB_PROGRAMACION_DETALLES> TB_PROGRAMACION_DETALLES { get; set; }
        public virtual DbSet<TB_PURIFICADOR> TB_PURIFICADOR { get; set; }
        public virtual DbSet<TB_REPORTE_VIAJE> TB_REPORTE_VIAJE { get; set; }
        public virtual DbSet<TB_TECNICO> TB_TECNICO { get; set; }
        public virtual DbSet<TB_UBIGEO> TB_UBIGEO { get; set; }
        public virtual DbSet<TB_USUARIO> TB_USUARIO { get; set; }
        public virtual DbSet<TB_VEHICULO> TB_VEHICULO { get; set; }
    }
}
