//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyKawsay_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ADMINISTRADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ADMINISTRADOR()
        {
            this.TB_ALMACEN = new HashSet<TB_ALMACEN>();
        }
    
        public string Cod_Adm { get; set; }
        public string Dni_Adm { get; set; }
        public string Nom_Adm { get; set; }
        public string Ape_Pat_Adm { get; set; }
        public string Ape_Mat_Adm { get; set; }
        public string Tel_Adm { get; set; }
        public string Dir_Adm { get; set; }
        public string Cor_Adm { get; set; }
        public System.DateTime Fec_Nac_Adm { get; set; }
        public string Cod_Ubi { get; set; }
        public byte[] Fot_Adm { get; set; }
        public string Est_Adm { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
    
        public virtual TB_UBIGEO TB_UBIGEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ALMACEN> TB_ALMACEN { get; set; }
    }
}
