//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyKawsay_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ALMACENAMIENTO
    {
        public string Cod_Alm { get; set; }
        public string Cod_Pur { get; set; }
        public bool Sto_Pur { get; set; }
    
        public virtual TB_ALMACEN TB_ALMACEN { get; set; }
        public virtual TB_PURIFICADOR TB_PURIFICADOR { get; set; }
    }
}
