//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyKawsay_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ALMACEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ALMACEN()
        {
            this.TB_ALMACENAMIENTO = new HashSet<TB_ALMACENAMIENTO>();
        }
    
        public string Cod_Alm { get; set; }
        public string Cod_Ubi { get; set; }
        public string Dir_Alm { get; set; }
        public short Cap_Alm { get; set; }
        public string Cod_Adm { get; set; }
    
        public virtual TB_ADMINISTRADOR TB_ADMINISTRADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ALMACENAMIENTO> TB_ALMACENAMIENTO { get; set; }
        public virtual TB_UBIGEO TB_UBIGEO { get; set; }
    }
}
