//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyKawsay_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CLIENTE()
        {
            this.TB_INSTALACION = new HashSet<TB_INSTALACION>();
            this.TB_PROGRAMACION_DETALLES = new HashSet<TB_PROGRAMACION_DETALLES>();
            this.TB_MANTENIMIENTO = new HashSet<TB_MANTENIMIENTO>();
        }
    
        public string Cod_Cli { get; set; }
        public string Dni_Cli { get; set; }
        public string Nom_Cli { get; set; }
        public string Ape_Pat_Cli { get; set; }
        public string Ape_Mat_Cli { get; set; }
        public string Tel_Cli { get; set; }
        public string Dir_Cli { get; set; }
        public string Cor_Cli { get; set; }
        public string Est_Cli { get; set; }
        public System.DateTime Fec_Nac_Cli { get; set; }
        public string Cod_Ubi { get; set; }
        public byte[] Fot_Cli { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
    
        public virtual TB_UBIGEO TB_UBIGEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_INSTALACION> TB_INSTALACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROGRAMACION_DETALLES> TB_PROGRAMACION_DETALLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MANTENIMIENTO> TB_MANTENIMIENTO { get; set; }
    }
}
