//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyKawsay_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MANTENIMIENTO
    {
        public string Cod_Man { get; set; }
        public string Obs_Man { get; set; }
        public System.DateTime Fec_Man { get; set; }
        public string Cod_Tec { get; set; }
        public string Cod_Cli { get; set; }
        public byte[] Fot_Man { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public string Est_Man { get; set; }
    
        public virtual TB_CLIENTE TB_CLIENTE { get; set; }
        public virtual TB_TECNICO TB_TECNICO { get; set; }
    }
}
