//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyKawsay_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PURIFICADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PURIFICADOR()
        {
            this.TB_ALMACENAMIENTO = new HashSet<TB_ALMACENAMIENTO>();
            this.TB_INSTALACION = new HashSet<TB_INSTALACION>();
        }
    
        public string Cod_Pur { get; set; }
        public string Tip_Pur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ALMACENAMIENTO> TB_ALMACENAMIENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_INSTALACION> TB_INSTALACION { get; set; }
    }
}
