//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyKawsay_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROGRAMACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PROGRAMACION()
        {
            this.TB_PROGRAMACION_DETALLES = new HashSet<TB_PROGRAMACION_DETALLES>();
        }
    
        public string Cod_Prog { get; set; }
        public string Cod_Tec { get; set; }
        public System.DateTime Fec_Ini { get; set; }
        public System.DateTime Fec_Fin { get; set; }
        public string Obs_Prog { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Registro { get; set; }
        public string Est_Prog { get; set; }
    
        public virtual TB_TECNICO TB_TECNICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROGRAMACION_DETALLES> TB_PROGRAMACION_DETALLES { get; set; }
    }
}
