//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyKawsay_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROGRAMACION_DETALLES
    {
        public int Id_Det { get; set; }
        public string Cod_Prog { get; set; }
        public string Cod_Cli { get; set; }
        public System.DateTime Fec_Visita { get; set; }
        public string Tip_Serv { get; set; }
        public string Obs_Det { get; set; }
    
        public virtual TB_CLIENTE TB_CLIENTE { get; set; }
        public virtual TB_PROGRAMACION TB_PROGRAMACION { get; set; }
    }
}
