//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyKawsay_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TECNICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_TECNICO()
        {
            this.TB_HERRAMIENTA = new HashSet<TB_HERRAMIENTA>();
            this.TB_INSTALACION = new HashSet<TB_INSTALACION>();
            this.TB_MANTENIMIENTO = new HashSet<TB_MANTENIMIENTO>();
            this.TB_PROGRAMACION = new HashSet<TB_PROGRAMACION>();
            this.TB_REPORTE_VIAJE = new HashSet<TB_REPORTE_VIAJE>();
        }
    
        public string Cod_Tec { get; set; }
        public string Dni_Tec { get; set; }
        public string Nom_Tec { get; set; }
        public string Ape_Pat_Tec { get; set; }
        public string Ape_Mat_Tec { get; set; }
        public string Tel_Tec { get; set; }
        public string Est_Tec { get; set; }
        public string Dir_Tec { get; set; }
        public string Cor_Tec { get; set; }
        public string Esp_Tec { get; set; }
        public string Lic_Tec { get; set; }
        public string Cod_Ubi { get; set; }
        public byte[] Fot_Tec { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Nac_Tec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_HERRAMIENTA> TB_HERRAMIENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_INSTALACION> TB_INSTALACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MANTENIMIENTO> TB_MANTENIMIENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROGRAMACION> TB_PROGRAMACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_REPORTE_VIAJE> TB_REPORTE_VIAJE { get; set; }
        public virtual TB_UBIGEO TB_UBIGEO { get; set; }
    }
}
