//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyKawsay_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_VEHICULO()
        {
            this.TB_REPORTE_VIAJE = new HashSet<TB_REPORTE_VIAJE>();
        }
    
        public string Cod_Veh { get; set; }
        public string Pla_Veh { get; set; }
        public string Est_Veh { get; set; }
        public byte[] Foto_Veh { get; set; }
        public string Mar_Veh { get; set; }
        public string Mod_Veh { get; set; }
        public string Num_Ser_Veh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_REPORTE_VIAJE> TB_REPORTE_VIAJE { get; set; }
    }
}
